'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getReport, saveReport, getProjects } from '@/lib/storage';
import { REPORT_SECTIONS } from '@/lib/constants';
import type { DailyReport, ReportSections, Project } from '@/types';
import { HardHat, ChevronLeft, Printer, Copy, Check, Pencil, Save, AlertCircle, Send, X, Link2, Mail } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { pushReport } from '@/lib/sync';

function formatPlainText(r: DailyReport) {
  const date = new Date(r.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
  return [
    'DAILY CONSTRUCTION REPORT',
    '═'.repeat(50),
    `Project:  ${r.projectName}`,
    `Date:     ${date}`,
    `Crew:     ${r.crewCount} workers`,
    `Weather:  ${r.weatherCondition}, ${r.temperature}`,
    '═'.repeat(50),
    '',
    ...REPORT_SECTIONS.map(({key,label}) => `${label.toUpperCase()}\n${'─'.repeat(label.length)}\n${r.sections[key]}`),
    '',
    '─'.repeat(50),
    'Generated by EndOfDay',
  ].join('\n\n');
}

export default function ReportViewer({ id }: { id: string }) {
  const [report, setReport]   = useState<DailyReport | null>(null);
  const [project, setProject] = useState<Project | undefined>();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft]     = useState<ReportSections | null>(null);
  const [copied, setCopied]         = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [notFound, setNotFound]     = useState(false);
  const [showSend, setShowSend]     = useState(false);
  const [sendCopied, setSendCopied] = useState(false);
  const [emailTo, setEmailTo]       = useState('');
  const [emailName, setEmailName]   = useState('');
  const [emailSending, setEmailSending] = useState(false);
  const [emailSent, setEmailSent]   = useState(false);
  const [emailError, setEmailError] = useState('');

  useEffect(() => {
    const r = getReport(id);
    if (!r) { setNotFound(true); return; }
    setReport(r);
    setDraft(r.sections);
    setProject(getProjects().find(p => p.id === r.projectId));
  }, [id]);

  function save() {
    if (!report || !draft) return;
    const updated = { ...report, sections: draft, status: 'final' as const };
    saveReport(updated);
    setReport(updated);
    setEditing(false);
    // Sync to cloud async (fire-and-forget)
    supabase.auth.getUser().then(({ data }) => {
      if (data.user) pushReport(updated, data.user.id).catch(() => {});
    });
  }

  const plainText = useMemo(() => (report ? formatPlainText(report) : ''), [report]);

  function copy() {
    navigator.clipboard.writeText(plainText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function copyShareLink() {
    if (!report) return;
    // Exclude photos — base64 images would make the URL too large for browsers
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { photos: _photos, ...reportWithoutPhotos } = report;
    const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(reportWithoutPhotos))));
    return `${window.location.origin}/report/share?d=${encoded}`;
  }

  async function shareOrCopyLink() {
    if (!report) return;
    const url = copyShareLink() ?? window.location.href;
    const title = `Daily Report — ${report.projectName}`;
    const date = new Date(report.date + 'T12:00:00').toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric',
    });
    const text = `${title} — ${date}`;

    // Use native share on mobile (WhatsApp, Messages, etc.)
    if (typeof navigator.share === 'function') {
      try {
        await navigator.share({ title, text, url });
        setShareCopied(true);
        setTimeout(() => setShareCopied(false), 2500);
        return;
      } catch {
        // User dismissed — fall through to clipboard
      }
    }
    // Desktop fallback: clipboard
    navigator.clipboard.writeText(url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2500);
  }

  function trySendEmail() {
    if (!report) return;
    const date = new Date(report.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
    const subject = encodeURIComponent(`Daily Report – ${report.projectName} – ${date}`);
    const body = encodeURIComponent(plainText);
    navigator.clipboard.writeText(plainText);
    setSendCopied(true);
    const mailto = `mailto:?subject=${subject}&body=${body}`;
    if (mailto.length < 2000) window.open(mailto);
  }

  async function sendViaApi(e: React.FormEvent) {
    e.preventDefault();
    if (!report || !emailTo.trim()) return;
    setEmailSending(true);
    setEmailError('');
    try {
      const { data } = await supabase.auth.getSession();
      const token = data.session?.access_token;
      const res = await fetch('/api/send-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          email: emailTo.trim(),
          recipientName: emailName.trim() || undefined,
          projectName: report.projectName,
          date: new Date(report.date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}),
          sections: report.sections,
        }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to send');
      setEmailSent(true);
    } catch (err) {
      setEmailError(err instanceof Error ? err.message : 'Failed to send');
    } finally {
      setEmailSending(false);
    }
  }

  if (notFound) return (
    <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center gap-4 text-center px-4">
      <AlertCircle size={40} className="text-slate-300" />
      <p className="text-slate-500 font-medium">Report not found on this device.</p>
      <p className="text-slate-400 text-sm max-w-xs">Reports are saved to this browser only. If someone sent you this link, ask them to use the Share Link button instead.</p>
      <Link href="/" className="text-amber-600 hover:underline text-sm font-semibold">← Back to dashboard</Link>
    </div>
  );

  if (!report || !draft) return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center">
      <div className="w-8 h-8 border-2 border-amber-500 border-t-transparent rounded-full animate-spin" />
    </div>
  );

  const formattedDate = new Date(report.date+'T12:00:00').toLocaleDateString('en-US',{
    weekday:'long', month:'long', day:'numeric', year:'numeric',
  });

  return (
    <div className="min-h-screen bg-slate-50">

      {/* ── Header ── */}
      <header className="bg-slate-950 border-b border-white/5 sticky top-0 z-10 no-print">
        <div className="max-w-3xl mx-auto px-5 py-4 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link href="/" aria-label="Back to dashboard" className="text-slate-500 hover:text-white transition-colors p-1 -ml-1 rounded-lg hover:bg-white/5">
              <ChevronLeft size={20} />
            </Link>
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 bg-amber-500 rounded-md flex items-center justify-center">
                <HardHat size={14} className="text-slate-900" />
              </div>
              <span className="text-white font-bold">EndOfDay</span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {editing ? (
              <>
                <button
                  onClick={() => { setEditing(false); setDraft(report.sections); }}
                  className="text-sm text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={save}
                  className="flex items-center gap-1.5 text-sm font-bold bg-amber-500 hover:bg-amber-400 text-slate-900 px-3 py-1.5 rounded-lg transition-all"
                >
                  <Save size={14} /> Save
                </button>
              </>
            ) : (
              <>
                <button
                  onClick={() => setEditing(true)}
                  className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  <Pencil size={13} /> Edit
                </button>
                <button
                  onClick={copy}
                  className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
                  {copied ? 'Copied!' : 'Copy'}
                </button>
                <button
                  onClick={shareOrCopyLink}
                  className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  {shareCopied ? <Check size={13} className="text-emerald-400" /> : <Link2 size={13} />}
                  {shareCopied ? 'Shared!' : 'Share'}
                </button>
                <button
                  onClick={() => { setShowSend(true); setSendCopied(false); }}
                  className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  <Send size={13} /> Send
                </button>
                <button
                  onClick={() => window.print()}
                  className="flex items-center gap-1.5 text-xs font-bold bg-amber-500 hover:bg-amber-400 text-slate-900 px-3 py-1.5 rounded-lg transition-all"
                >
                  <Printer size={13} /> Print / PDF
                </button>
              </>
            )}
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 py-8 space-y-4 animate-fade-up">

        {/* ── Report cover card ── */}
        <div className="bg-slate-950 text-white rounded-2xl overflow-hidden shadow-xl report-cover-print">
          {/* Amber top stripe */}
          <div className="h-1.5 bg-gradient-to-r from-amber-400 to-orange-500" />
          <div className="p-7">
            <div className="flex items-start justify-between flex-wrap gap-4">
              <div>
                <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">
                  Daily Construction Report
                </div>
                <h1 className="text-2xl font-extrabold text-white leading-tight">{report.projectName}</h1>
                {project?.address && (
                  <div className="text-slate-400 text-sm mt-1">{project.address}</div>
                )}
              </div>
              <span className={`text-xs font-bold px-3 py-1.5 rounded-full ${
                report.status === 'final'
                  ? 'bg-emerald-500/15 text-emerald-400 ring-1 ring-emerald-500/30'
                  : 'bg-amber-500/15 text-amber-400 ring-1 ring-amber-500/30'
              }`}>
                {report.status === 'final' ? '✓ Final' : 'Draft'}
              </span>
            </div>

            {/* Key facts grid */}
            <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: 'Date',    value: formattedDate },
                { label: 'Crew',    value: `${report.crewCount} workers` },
                { label: 'Weather', value: report.weatherCondition },
                { label: 'Temp',    value: report.temperature },
              ].map(({ label, value }) => (
                <div key={label} className="bg-white/5 rounded-xl px-4 py-3">
                  <div className="text-xs text-slate-500 mb-1 font-semibold">{label}</div>
                  <div className="text-sm text-white font-medium leading-tight">{value}</div>
                </div>
              ))}
            </div>

            {/* Project meta */}
            {project && (project.clientName || project.gcName || project.superintendentName) && (
              <div className="mt-4 pt-4 border-t border-white/10 flex flex-wrap gap-5 text-xs text-slate-400">
                {project.clientName && <span><span className="text-slate-600">Owner:</span> {project.clientName}</span>}
                {project.gcName && <span><span className="text-slate-600">GC:</span> {project.gcName}</span>}
                {project.superintendentName && <span><span className="text-slate-600">Super:</span> {project.superintendentName}</span>}
              </div>
            )}
          </div>
        </div>

        {/* ── Sections ── */}
        {REPORT_SECTIONS.map(({ key, label, color }) => (
          <div
            key={key}
            className={`bg-white rounded-2xl border border-slate-100 border-l-4 ${color} shadow-sm overflow-hidden report-card hover:shadow-md transition-shadow`}
          >
            <div className="px-5 py-3 border-b border-slate-100 bg-slate-50/60">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{label}</span>
            </div>
            <div className="px-5 py-4">
              {editing ? (
                <textarea
                  rows={Math.max(2, Math.ceil(draft[key].length / 90))}
                  value={draft[key]}
                  onChange={e => setDraft(prev => prev ? { ...prev, [key]: e.target.value } : prev)}
                  className="w-full text-sm text-slate-700 leading-relaxed focus:outline-none resize-none bg-transparent border-b-2 border-dashed border-amber-300 pb-1"
                />
              ) : (
                <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{report.sections[key]}</p>
              )}
            </div>
          </div>
        ))}

        {/* ── Photo grid ── */}
        {report.photos && report.photos.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-100 border-l-4 border-l-blue-300 shadow-sm overflow-hidden report-card">
            <div className="px-5 py-3 border-b border-slate-100 bg-slate-50/60">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                Site Photos ({report.photos.length})
              </span>
            </div>
            <div className="p-4 grid grid-cols-2 sm:grid-cols-3 gap-3">
              {report.photos.map((src, i) => (
                <div key={i} className="relative aspect-video bg-slate-100 rounded-xl overflow-hidden">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={src} alt={`Site photo ${i + 1}`} className="w-full h-full object-cover" />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Signature block (print only) ── */}
        <div className="print-signature grid grid-cols-2 gap-12 text-sm text-slate-600">
          <div>
            <div className="border-b border-slate-300 mb-2 h-10" />
            <div className="font-semibold">Superintendent Signature</div>
            <div className="text-slate-400 text-xs">{project?.superintendentName || 'Name'} · Date: {report.date}</div>
          </div>
          <div>
            <div className="border-b border-slate-300 mb-2 h-10" />
            <div className="font-semibold">GC / Owner Acknowledgment</div>
            <div className="text-slate-400 text-xs">{project?.gcName || 'Company'} · Date: ___________</div>
          </div>
        </div>

        {/* ── Footer ── */}
        <div className="text-center text-xs text-slate-300 pt-4 pb-8 no-print">
          Generated {new Date(report.createdAt).toLocaleString()} · Powered by EndOfDay
        </div>
      </main>

      {/* ── Send modal ── */}
      {showSend && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-end sm:items-center justify-center z-50 p-4 no-print animate-fade-in">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg animate-fade-up">
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100">
              <h3 className="font-bold text-slate-900">Send report</h3>
              <button
                onClick={() => { setShowSend(false); setEmailSent(false); setEmailError(''); setEmailTo(''); setEmailName(''); }}
                className="text-slate-400 hover:text-slate-600 transition-colors"
              >
                <X size={18} />
              </button>
            </div>
            <div className="px-5 py-5 space-y-5">

              {/* Email via EndOfDay */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Mail size={14} className="text-amber-500" />
                  <span className="text-sm font-semibold text-slate-700">Email this report</span>
                </div>
                {emailSent ? (
                  <div className="flex items-center gap-3 bg-emerald-50 text-emerald-700 rounded-xl px-4 py-3 text-sm font-semibold">
                    <Check size={16} className="text-emerald-600" />
                    Report sent to {emailTo}
                  </div>
                ) : (
                  <form onSubmit={sendViaApi} className="space-y-2.5">
                    <input
                      type="text"
                      placeholder="Recipient name (optional)"
                      value={emailName}
                      onChange={e => setEmailName(e.target.value)}
                      className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400"
                    />
                    <div className="flex gap-2">
                      <input
                        type="email"
                        required
                        placeholder="recipient@company.com"
                        value={emailTo}
                        onChange={e => setEmailTo(e.target.value)}
                        className="flex-1 border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400"
                      />
                      <button
                        type="submit"
                        disabled={emailSending || !emailTo.trim()}
                        className="flex items-center gap-1.5 bg-amber-500 hover:bg-amber-400 disabled:opacity-50 text-slate-900 font-bold px-4 py-2 rounded-lg text-sm transition-all"
                      >
                        {emailSending
                          ? <div className="w-4 h-4 border-2 border-slate-900 border-t-transparent rounded-full animate-spin" />
                          : <><Send size={13} /> Send</>
                        }
                      </button>
                    </div>
                    {emailError && (
                      <p className="text-xs text-red-600 bg-red-50 rounded-lg px-3 py-2">{emailError}</p>
                    )}
                  </form>
                )}
              </div>

              <div className="border-t border-slate-100" />

              {/* Clipboard fallback */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Copy size={14} className="text-slate-400" />
                  <span className="text-sm font-semibold text-slate-500">Or copy plain text</span>
                </div>
                <div className="flex gap-2.5">
                  <button
                    onClick={trySendEmail}
                    className="flex-1 flex items-center justify-center gap-2 border-2 border-slate-200 text-slate-600 font-semibold py-2.5 rounded-xl text-sm hover:border-slate-300 transition-all"
                  >
                    {sendCopied ? <Check size={14} className="text-emerald-500" /> : <Send size={14} />}
                    {sendCopied ? 'Copied!' : 'Copy & open email'}
                  </button>
                  <button
                    onClick={() => { navigator.clipboard.writeText(plainText); setSendCopied(true); }}
                    className="flex items-center gap-2 border-2 border-slate-200 text-slate-600 font-semibold px-4 py-2.5 rounded-xl text-sm hover:border-slate-300 transition-all"
                  >
                    <Copy size={14} />
                    Copy
                  </button>
                </div>
              </div>

            </div>
          </div>
        </div>
      )}
    </div>
  );
}
