'use client';

import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import Link from 'next/link';
import { REPORT_SECTIONS } from '@/lib/constants';
import type { DailyReport } from '@/types';
import { HardHat, Printer, Copy, Check, AlertCircle, ArrowRight } from 'lucide-react';

function decodeReport(encoded: string): DailyReport | null {
  try {
    return JSON.parse(decodeURIComponent(escape(atob(encoded))));
  } catch {
    return null;
  }
}

export default function ShareViewer() {
  const params = useSearchParams();
  const [copied, setCopied] = useState(false);

  const encoded = params.get('d');
  const report = encoded ? decodeReport(encoded) : null;

  function copy() {
    if (!report) return;
    const date = new Date(report.date + 'T12:00:00').toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
    const text = [
      'DAILY CONSTRUCTION REPORT',
      '═'.repeat(50),
      `Project:  ${report.projectName}`,
      `Date:     ${date}`,
      `Crew:     ${report.crewCount} workers`,
      `Weather:  ${report.weatherCondition}, ${report.temperature}`,
      '═'.repeat(50),
      '',
      ...REPORT_SECTIONS.map(({ key, label }) =>
        `${label.toUpperCase()}\n${'─'.repeat(label.length)}\n${report.sections[key]}`
      ),
      '',
      '─'.repeat(50),
      'Generated by EndOfDay',
    ].join('\n\n');
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center gap-4 text-center px-4">
        <AlertCircle size={40} className="text-slate-300" />
        <p className="text-slate-500 font-medium">This report link is invalid or has expired.</p>
        <Link href="/" className="text-amber-600 hover:underline text-sm font-semibold">
          Create your own reports →
        </Link>
      </div>
    );
  }

  const formattedDate = new Date(report.date + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric', year: 'numeric',
  });

  return (
    <div className="min-h-screen bg-slate-50">

      {/* ── Header ── */}
      <header className="bg-slate-950 border-b border-white/5 sticky top-0 z-10 no-print">
        <div className="max-w-3xl mx-auto px-5 py-4 flex items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 bg-amber-500 rounded-md flex items-center justify-center">
              <HardHat size={14} className="text-slate-900" />
            </div>
            <span className="text-white font-bold">EndOfDay</span>
            <span className="text-slate-600 text-xs font-medium ml-1">Shared Report</span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={copy}
              className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
            >
              {copied ? <Check size={13} className="text-emerald-400" /> : <Copy size={13} />}
              {copied ? 'Copied!' : 'Copy text'}
            </button>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 text-xs font-bold bg-amber-500 hover:bg-amber-400 text-slate-900 px-3 py-1.5 rounded-lg transition-all"
            >
              <Printer size={13} /> Print / PDF
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 py-8 space-y-4">

        {/* ── Cover card ── */}
        <div className="bg-slate-950 text-white rounded-2xl overflow-hidden shadow-xl report-cover-print">
          <div className="h-1.5 bg-gradient-to-r from-amber-400 to-orange-500" />
          <div className="p-7">
            <div className="flex items-start justify-between flex-wrap gap-4">
              <div>
                <div className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-2">
                  Daily Construction Report
                </div>
                <h1 className="text-2xl font-extrabold text-white leading-tight">{report.projectName}</h1>
              </div>
              <span className="text-xs font-bold px-3 py-1.5 rounded-full bg-emerald-500/15 text-emerald-400 ring-1 ring-emerald-500/30">
                ✓ Final
              </span>
            </div>
            <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4">
              {[
                { label: 'Date',    value: formattedDate },
                { label: 'Crew',    value: `${report.crewCount} workers` },
                { label: 'Weather', value: report.weatherCondition },
                { label: 'Temp',    value: report.temperature },
              ].map(({ label, value }) => (
                <div key={label} className="bg-white/5 rounded-xl px-4 py-3">
                  <div className="text-xs text-slate-500 mb-1 font-semibold">{label}</div>
                  <div className="text-sm text-white font-medium leading-tight">{value}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ── Sections ── */}
        {REPORT_SECTIONS.map(({ key, label, color }) => (
          <div
            key={key}
            className={`bg-white rounded-2xl border border-l-4 ${color} border-slate-100 shadow-sm overflow-hidden report-card`}
          >
            <div className="px-5 py-3 border-b border-slate-100 bg-slate-50/60">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{label}</span>
            </div>
            <div className="px-5 py-4">
              <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-wrap">{report.sections[key]}</p>
            </div>
          </div>
        ))}

        {/* ── Signature block (print only) ── */}
        <div className="print-signature grid grid-cols-2 gap-12 text-sm text-slate-600">
          <div>
            <div className="border-b border-slate-300 mb-2 h-10" />
            <div className="font-semibold">Superintendent Signature</div>
            <div className="text-slate-400 text-xs">Date: {report.date}</div>
          </div>
          <div>
            <div className="border-b border-slate-300 mb-2 h-10" />
            <div className="font-semibold">GC / Owner Acknowledgment</div>
            <div className="text-slate-400 text-xs">Date: ___________</div>
          </div>
        </div>

        {/* ── CTA (every shared report is a billboard) ── */}
        <div className="no-print bg-amber-50 border border-amber-200 rounded-2xl p-6 text-center">
          <p className="text-sm font-semibold text-slate-700 mb-1">This report was created in under 60 seconds.</p>
          <p className="text-xs text-slate-500 mb-4">Speak your end-of-day notes. AI writes the report.</p>
          <Link
            href="/"
            className="inline-flex items-center gap-2 bg-amber-500 hover:bg-amber-400 text-slate-900 font-bold px-5 py-2.5 rounded-xl text-sm transition-all shadow-lg shadow-amber-500/20"
          >
            Try EndOfDay free <ArrowRight size={15} />
          </Link>
        </div>

        <div className="text-center text-xs text-slate-300 pt-2 pb-8 no-print">
          Generated by EndOfDay · endofday.ai
        </div>
      </main>
    </div>
  );
}
